import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import * as nodemailer from 'nodemailer';

@Injectable()
export class EmailService {
  private readonly logger = new Logger(EmailService.name);
  private transporter: nodemailer.Transporter;

  constructor(private config: ConfigService) {
    const host = this.config.get<string>('SMTP_HOST', '');
    if (host) {
      this.transporter = nodemailer.createTransport({
        host,
        port: this.config.get<number>('SMTP_PORT', 587),
        secure: this.config.get<string>('SMTP_SECURE', 'false') === 'true',
        auth: {
          user: this.config.get<string>('SMTP_USER', ''),
          pass: this.config.get<string>('SMTP_PASS', ''),
        },
      });
      this.logger.log(`Email configured: ${host}:${this.config.get('SMTP_PORT', 587)}`);
    } else {
      this.logger.warn('SMTP not configured — emails will be logged but not sent');
    }
  }

  private get fromAddress(): string {
    return this.config.get<string>('SMTP_FROM', 'noreply@leanpilot.me');
  }

  async send(to: string, subject: string, html: string): Promise<boolean> {
    if (!this.transporter) {
      this.logger.log(`[DRY RUN] Email to=${to} subject="${subject}"`);
      return false;
    }

    try {
      await this.transporter.sendMail({
        from: `"LeanPilot" <${this.fromAddress}>`,
        to,
        subject,
        html,
      });
      this.logger.log(`Email sent to=${to} subject="${subject}"`);
      return true;
    } catch (err) {
      this.logger.error(`Email failed to=${to}: ${err instanceof Error ? err.message : err}`);
      return false;
    }
  }

  // ── Templates ──────────────────────────────────────────────────

  async sendPasswordReset(to: string, name: string, resetUrl: string): Promise<boolean> {
    return this.send(to, 'LeanPilot — Password Reset', `
      <div style="font-family: Arial, sans-serif; max-width: 480px; margin: 0 auto;">
        <div style="background: #1e40af; padding: 24px; border-radius: 8px 8px 0 0;">
          <h1 style="color: white; margin: 0; font-size: 20px;">LeanPilot</h1>
        </div>
        <div style="padding: 24px; background: #f9fafb; border: 1px solid #e5e7eb; border-top: none; border-radius: 0 0 8px 8px;">
          <p>Hi ${name},</p>
          <p>You requested a password reset. Click the button below to set a new password:</p>
          <div style="text-align: center; margin: 24px 0;">
            <a href="${resetUrl}" style="background: #2563eb; color: white; padding: 12px 32px; border-radius: 6px; text-decoration: none; font-weight: bold;">Reset Password</a>
          </div>
          <p style="font-size: 13px; color: #6b7280;">This link expires in 1 hour. If you didn't request this, ignore this email.</p>
        </div>
      </div>
    `);
  }

  async sendEscalationAlert(to: string, name: string, data: {
    ruleName: string;
    triggerType: string;
    workstationName?: string;
    durationMinutes?: number;
    tier: number;
    siteName: string;
  }): Promise<boolean> {
    const tierColor = data.tier >= 3 ? '#dc2626' : data.tier >= 2 ? '#f97316' : '#eab308';
    const tierLabel = `Level ${data.tier}`;

    return this.send(to, `LeanPilot Alert — ${data.ruleName}`, `
      <div style="font-family: Arial, sans-serif; max-width: 480px; margin: 0 auto;">
        <div style="background: ${tierColor}; padding: 24px; border-radius: 8px 8px 0 0;">
          <h1 style="color: white; margin: 0; font-size: 20px;">Escalation Alert — ${tierLabel}</h1>
          <p style="color: rgba(255,255,255,0.9); margin: 8px 0 0; font-size: 14px;">${data.siteName}</p>
        </div>
        <div style="padding: 24px; background: #f9fafb; border: 1px solid #e5e7eb; border-top: none; border-radius: 0 0 8px 8px;">
          <p>Hi ${name},</p>
          <table style="width: 100%; font-size: 14px; border-collapse: collapse;">
            <tr><td style="padding: 8px 0; color: #6b7280;">Rule</td><td style="padding: 8px 0; font-weight: bold;">${data.ruleName}</td></tr>
            <tr><td style="padding: 8px 0; color: #6b7280;">Trigger</td><td style="padding: 8px 0;">${data.triggerType.replace('_', ' ')}</td></tr>
            ${data.workstationName ? `<tr><td style="padding: 8px 0; color: #6b7280;">Workstation</td><td style="padding: 8px 0; font-weight: bold;">${data.workstationName}</td></tr>` : ''}
            ${data.durationMinutes ? `<tr><td style="padding: 8px 0; color: #6b7280;">Duration</td><td style="padding: 8px 0; color: ${tierColor}; font-weight: bold;">${data.durationMinutes} min</td></tr>` : ''}
          </table>
          <p style="margin-top: 16px; font-size: 13px; color: #6b7280;">Respond immediately. This alert was auto-generated by the LeanPilot escalation engine.</p>
        </div>
      </div>
    `);
  }
}
