import { Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { DashboardService } from '../dashboard/dashboard.service';

// eslint-disable-next-line @typescript-eslint/no-var-requires
const PdfPrinter = require('pdfmake');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const pdfFonts = require('pdfmake/build/vfs_fonts');

function createPrinter() {
  const vfs = pdfFonts.pdfMake.vfs;
  return new PdfPrinter({
    Roboto: {
      normal: Buffer.from(vfs['Roboto-Regular.ttf'], 'base64'),
      bold: Buffer.from(vfs['Roboto-Medium.ttf'], 'base64'),
      italics: Buffer.from(vfs['Roboto-Italic.ttf'], 'base64'),
      bolditalics: Buffer.from(vfs['Roboto-MediumItalic.ttf'], 'base64'),
    },
  });
}

function generatePdfBuffer(docDef: any): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const printer = createPrinter();
    const doc = printer.createPdfKitDocument(docDef);
    const chunks: Buffer[] = [];
    doc.on('data', (c: Buffer) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
    doc.end();
  });
}

@Injectable()
export class ReportsService {
  constructor(
    private prisma: PrismaService,
    private dashboard: DashboardService,
  ) {}

  // ===== TEMPLATE CRUD =====

  async getTemplate(siteId: string) {
    return this.prisma.reportTemplate.findUnique({ where: { siteId } });
  }

  async upsertTemplate(siteId: string, data: {
    companyName: string;
    logoUrl?: string;
    headerText?: string;
    accentColor?: string;
    footerText?: string;
  }) {
    return this.prisma.reportTemplate.upsert({
      where: { siteId },
      create: { siteId, ...data },
      update: data,
    });
  }

  // ===== COMMON HEADER/FOOTER =====

  private async getHeaderFooter(siteId: string) {
    const tmpl = await this.prisma.reportTemplate.findUnique({ where: { siteId } });
    const site = await this.prisma.site.findUnique({ where: { id: siteId } });
    return {
      companyName: tmpl?.companyName || site?.name || 'LeanPilot',
      accentColor: tmpl?.accentColor || '#2563eb',
      headerText: tmpl?.headerText || '',
      footerText: tmpl?.footerText || `Generated by LeanPilot — ${new Date().toLocaleDateString()}`,
    };
  }

  // ===== 5S AUDIT REPORT =====

  async generateFiveSReport(auditId: string, siteId: string): Promise<Buffer> {
    const audit = await this.prisma.fiveSAudit.findFirst({
      where: { id: auditId, siteId },
      include: {
        scores: true,
        auditor: { select: { firstName: true, lastName: true } },
      },
    });
    if (!audit) throw new NotFoundException('5S Audit not found');

    const hf = await this.getHeaderFooter(siteId);
    const categories = ['sort', 'set_in_order', 'shine', 'standardize', 'sustain', 'safety'];
    const categoryLabels: Record<string, string> = {
      sort: 'Sort (Seiri)', set_in_order: 'Set in Order (Seiton)', shine: 'Shine (Seiso)',
      standardize: 'Standardize (Seiketsu)', sustain: 'Sustain (Shitsuke)', safety: 'Safety',
    };

    const scoreRows = categories.map(cat => {
      const score = audit.scores.find(s => s.category === cat);
      return [categoryLabels[cat] || cat, `${score?.score || 0} / 5`, score?.notes || '—'];
    });

    const docDef = {
      content: [
        { text: hf.companyName, style: 'companyName' },
        hf.headerText ? { text: hf.headerText, style: 'headerText' } : null,
        { text: '5S / 6S Audit Report', style: 'title' },
        { text: ' ', margin: [0, 5] },
        {
          columns: [
            { text: `Area: ${audit.area}`, style: 'field' },
            { text: `Date: ${new Date(audit.createdAt).toLocaleDateString()}`, style: 'field', alignment: 'right' },
          ],
        },
        {
          columns: [
            { text: `Auditor: ${audit.auditor.firstName} ${audit.auditor.lastName}`, style: 'field' },
            { text: `Status: ${audit.status}`, style: 'field', alignment: 'right' },
          ],
        },
        { text: ' ', margin: [0, 10] },
        { text: `Overall Score: ${audit.totalScore} / 30 (${audit.percentage}%)`, style: 'scoreHeader', color: audit.percentage >= 80 ? '#16a34a' : audit.percentage >= 60 ? '#ca8a04' : '#dc2626' },
        { text: ' ', margin: [0, 10] },
        {
          table: {
            headerRows: 1,
            widths: ['*', 60, '*'],
            body: [
              [{ text: 'Category', style: 'tableHeader' }, { text: 'Score', style: 'tableHeader' }, { text: 'Notes', style: 'tableHeader' }],
              ...scoreRows,
            ],
          },
          layout: 'lightHorizontalLines',
        },
        audit.notes ? { text: `\nAudit Notes: ${audit.notes}`, style: 'notes', margin: [0, 15, 0, 0] } : null,
      ].filter(Boolean),
      footer: { text: hf.footerText, alignment: 'center', fontSize: 8, color: '#9ca3af', margin: [0, 10] },
      defaultStyle: { font: 'Roboto', fontSize: 10 },
      styles: {
        companyName: { fontSize: 14, bold: true, color: hf.accentColor, margin: [0, 0, 0, 2] },
        headerText: { fontSize: 9, color: '#6b7280', margin: [0, 0, 0, 10] },
        title: { fontSize: 18, bold: true, margin: [0, 10, 0, 5] },
        field: { fontSize: 10, color: '#374151', margin: [0, 2] },
        scoreHeader: { fontSize: 14, bold: true, margin: [0, 5] },
        tableHeader: { bold: true, fontSize: 10, color: '#1f2937' },
        notes: { fontSize: 9, italics: true, color: '#6b7280' },
      },
    };

    return generatePdfBuffer(docDef);
  }

  // ===== GEMBA WALK REPORT =====

  async generateGembaReport(walkId: string, siteId: string): Promise<Buffer> {
    const walk = await this.prisma.gembaWalk.findFirst({
      where: { id: walkId, siteId },
      include: {
        walker: { select: { firstName: true, lastName: true } },
        observations: { orderBy: { createdAt: 'asc' } },
      },
    });
    if (!walk) throw new NotFoundException('Gemba Walk not found');

    const hf = await this.getHeaderFooter(siteId);

    const wasteLabels: Record<string, string> = {
      waiting: 'Waiting', overproduction: 'Overproduction', inventory: 'Excess Inventory',
      motion: 'Motion', transportation: 'Transportation', over_processing: 'Over-processing',
      defect: 'Defects', talent: 'Unused Talent',
    };

    const obsRows = walk.observations.map((obs, i) => [
      `${i + 1}`,
      wasteLabels[obs.wasteCategory] || obs.wasteCategory,
      obs.severity.toUpperCase(),
      obs.description,
      obs.status,
    ]);

    // Severity breakdown
    const high = walk.observations.filter(o => o.severity === 'high').length;
    const medium = walk.observations.filter(o => o.severity === 'medium').length;
    const low = walk.observations.filter(o => o.severity === 'low').length;

    const docDef = {
      content: [
        { text: hf.companyName, style: 'companyName' },
        { text: 'Gemba Walk Report', style: 'title' },
        { text: ' ', margin: [0, 5] },
        {
          columns: [
            { text: `Walker: ${walk.walker.firstName} ${walk.walker.lastName}`, style: 'field' },
            { text: `Date: ${walk.date}`, style: 'field', alignment: 'right' },
          ],
        },
        { text: `Status: ${walk.status} | Observations: ${walk.observations.length} (H:${high} M:${medium} L:${low})`, style: 'field', margin: [0, 5, 0, 15] },
        walk.observations.length > 0 ? {
          table: {
            headerRows: 1,
            widths: [20, 80, 50, '*', 60],
            body: [
              ['#', 'Waste Type', 'Severity', 'Description', 'Status'].map(h => ({ text: h, style: 'tableHeader' })),
              ...obsRows,
            ],
          },
          layout: 'lightHorizontalLines',
        } : { text: 'No observations recorded.', style: 'notes' },
      ],
      footer: { text: hf.footerText, alignment: 'center', fontSize: 8, color: '#9ca3af', margin: [0, 10] },
      defaultStyle: { font: 'Roboto', fontSize: 9 },
      styles: {
        companyName: { fontSize: 14, bold: true, color: hf.accentColor, margin: [0, 0, 0, 2] },
        title: { fontSize: 18, bold: true, margin: [0, 10, 0, 5] },
        field: { fontSize: 10, color: '#374151', margin: [0, 2] },
        tableHeader: { bold: true, fontSize: 9, color: '#1f2937' },
        notes: { fontSize: 10, italics: true, color: '#6b7280' },
      },
    };

    return generatePdfBuffer(docDef);
  }

  // ===== NCR REPORT (8D-style) =====

  async generateNcrReport(ncrId: string, siteId: string): Promise<Buffer> {
    const ncr = await this.prisma.nonConformanceReport.findFirst({
      where: { id: ncrId, siteId },
      include: {
        reporter: { select: { firstName: true, lastName: true } },
        attachments: true,
      },
    });
    if (!ncr) throw new NotFoundException('NCR not found');

    const hf = await this.getHeaderFooter(siteId);

    const sections = [
      { label: 'D1 — Description', value: ncr.description },
      { label: 'D2 — Severity', value: ncr.severity.toUpperCase() },
      { label: 'D3 — Root Cause', value: ncr.rootCause || 'Pending investigation' },
      { label: 'D4 — Containment Action', value: ncr.containmentAction || 'Not defined' },
      { label: 'D5 — Corrective Action', value: ncr.correctiveAction || 'Not defined' },
      { label: 'D6 — Verification', value: ncr.status === 'verified' ? 'Verified and closed' : 'Pending' },
    ];

    const docDef = {
      content: [
        { text: hf.companyName, style: 'companyName' },
        { text: 'Non-Conformance Report (8D)', style: 'title' },
        { text: ' ', margin: [0, 5] },
        {
          columns: [
            { text: `NCR: ${ncr.title}`, style: 'field', bold: true },
            { text: `Date: ${new Date(ncr.createdAt).toLocaleDateString()}`, style: 'field', alignment: 'right' },
          ],
        },
        {
          columns: [
            { text: `Reported by: ${ncr.reporter.firstName} ${ncr.reporter.lastName}`, style: 'field' },
            { text: `Status: ${ncr.status}`, style: 'field', alignment: 'right' },
          ],
        },
        { text: ' ', margin: [0, 15] },
        ...sections.map(s => ([
          { text: s.label, style: 'sectionTitle' },
          { text: s.value, style: 'sectionBody', margin: [0, 2, 0, 12] },
        ])).flat(),
        ncr.attachments.length > 0 ? { text: `Attachments: ${ncr.attachments.map(a => a.fileName).join(', ')}`, style: 'notes', margin: [0, 10] } : null,
      ].filter(Boolean),
      footer: { text: hf.footerText, alignment: 'center', fontSize: 8, color: '#9ca3af', margin: [0, 10] },
      defaultStyle: { font: 'Roboto', fontSize: 10 },
      styles: {
        companyName: { fontSize: 14, bold: true, color: hf.accentColor, margin: [0, 0, 0, 2] },
        title: { fontSize: 18, bold: true, margin: [0, 10, 0, 5] },
        field: { fontSize: 10, color: '#374151', margin: [0, 2] },
        sectionTitle: { fontSize: 11, bold: true, color: '#1f2937' },
        sectionBody: { fontSize: 10, color: '#374151' },
        notes: { fontSize: 9, italics: true, color: '#6b7280' },
      },
    };

    return generatePdfBuffer(docDef);
  }

  // ===== OEE SUMMARY REPORT =====

  async generateOeeReport(siteId: string, period = 'week'): Promise<Buffer> {
    const oeeData = await this.dashboard.getOee(siteId, undefined, period) as any;
    // getOee returns { period, since, workstations: [...], siteOee }
    const arr = Array.isArray(oeeData?.workstations) ? oeeData.workstations : [];
    const hf = await this.getHeaderFooter(siteId);

    // Values from dashboard are already percentages (e.g. 85.0 = 85%)
    let totalProd = 0, totalScrap = 0;
    for (const ws of arr) {
      totalProd += ws.totalProduced;
      totalScrap += ws.totalScrap;
    }
    const oee = oeeData?.siteOee ?? 0;

    // Values are already percentages (e.g. 85.0 = 85%)
    const wsRows = arr.map(ws => [
      ws.workstationName,
      `${ws.oee}%`,
      `${ws.availability}%`,
      `${ws.performance}%`,
      `${ws.quality}%`,
      `${ws.totalProduced}`,
    ]);

    // Compute weighted averages for the summary line
    const avgA = arr.length > 0 ? Math.round(arr.reduce((s, w) => s + w.availability, 0) / arr.length * 10) / 10 : 0;
    const avgP = arr.length > 0 ? Math.round(arr.reduce((s, w) => s + w.performance, 0) / arr.length * 10) / 10 : 0;
    const avgQ = arr.length > 0 ? Math.round(arr.reduce((s, w) => s + w.quality, 0) / arr.length * 10) / 10 : 0;

    const docDef = {
      content: [
        { text: hf.companyName, style: 'companyName' },
        { text: `OEE Summary Report — ${period}`, style: 'title' },
        { text: `Period: Last ${period} | Generated: ${new Date().toLocaleDateString()}`, style: 'field', margin: [0, 5, 0, 15] },
        {
          columns: [
            { text: `OEE: ${oee}%`, style: 'bigMetric', color: oee >= 85 ? '#16a34a' : oee >= 60 ? '#ca8a04' : '#dc2626' },
            { text: `A: ${avgA}%  |  P: ${avgP}%  |  Q: ${avgQ}%`, style: 'subMetric' },
          ],
        },
        { text: `Produced: ${totalProd} | Scrap: ${totalScrap}`, style: 'field', margin: [0, 5, 0, 15] },
        arr.length > 0 ? {
          table: {
            headerRows: 1,
            widths: ['*', 50, 50, 50, 50, 50],
            body: [
              ['Workstation', 'OEE', 'Avail.', 'Perf.', 'Quality', 'Produced'].map(h => ({ text: h, style: 'tableHeader' })),
              ...wsRows,
            ],
          },
          layout: 'lightHorizontalLines',
        } : { text: 'No production data for this period.', style: 'notes' },
      ],
      footer: { text: hf.footerText, alignment: 'center', fontSize: 8, color: '#9ca3af', margin: [0, 10] },
      defaultStyle: { font: 'Roboto', fontSize: 10 },
      styles: {
        companyName: { fontSize: 14, bold: true, color: hf.accentColor, margin: [0, 0, 0, 2] },
        title: { fontSize: 18, bold: true, margin: [0, 10, 0, 5] },
        field: { fontSize: 10, color: '#374151', margin: [0, 2] },
        bigMetric: { fontSize: 24, bold: true },
        subMetric: { fontSize: 12, color: '#6b7280', margin: [10, 8, 0, 0] },
        tableHeader: { bold: true, fontSize: 9, color: '#1f2937' },
        notes: { fontSize: 10, italics: true, color: '#6b7280' },
      },
    };

    return generatePdfBuffer(docDef);
  }
}
